"""Summarises the benchmark runs in docs/performance/ into tables and charts.

    python3 docs/performance/analyse.py

Needs Python 3 and matplotlib (only for the charts; a developer tool, not part
of the game). Reads every summary.json / frames.csv written by
tools/benchmark.gd and writes:
    docs/performance/results.md        tables used in docs/phase-13-performance.md
    docs/performance/chart_*.png       charts
"""
import csv
import glob
import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
SURFACE, INK, INK2, GRID = "#fcfcfb", "#0b0b0b", "#52514e", "#e4e3df"
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100"]  # categorical slots 1-4
BEFORE, AFTER = "#a7a6a1", "#2a78d6"
SCENARIOS = [("normal", 3), ("several", 8), ("stress", 24)]
STAGES = [("baseline", "Before (4 cascades, 4096 atlas)"),
          ("after_2splits", "2 cascades"),
          ("after_2splits_2048", "After (2 cascades, 2048 atlas)")]


def load(pattern):
    out = []
    for f in sorted(glob.glob(os.path.join(HERE, pattern, "summary.json"))):
        s = json.load(open(f))
        s["_dir"] = os.path.dirname(f)
        out.append(s)
    return out


def m(s, key, stat="mean"):
    return s["metrics"][key][stat]


def avg(runs, fn):
    vals = [fn(r) for r in runs]
    return statistics.mean(vals) if vals else float("nan")


def spread(runs, fn):
    vals = [fn(r) for r in runs]
    return (min(vals), max(vals)) if vals else (float("nan"), float("nan"))


def runs_for(stage, mode, scenario):
    return load(f"{stage}/{mode}/{scenario}_r*")


def style(ax, title, ylabel):
    ax.set_facecolor(SURFACE)
    ax.set_title(title, loc="left", color=INK, fontsize=12, pad=10)
    ax.set_ylabel(ylabel, color=INK2)
    ax.tick_params(colors=INK2)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def tables():
    lines = ["# Benchmark results", "",
             "Generated by `docs/performance/analyse.py` from the runs in this folder. "
             "Means of the repeated runs (range in brackets).", ""]
    # Rendering, before/after.
    lines += ["## Rendering runs (1280×720, Xvfb + Mesa llvmpipe)", "",
              "| Scenario | Guards | Stage | Runs | Avg FPS | 1% low FPS | Frame ms mean | Frame ms p95 | Render CPU ms | Render GPU ms | Scripts ms (physics + process) | Other ms | Draw calls | Objects | Primitives |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for sc, g in SCENARIOS:
        for stage, label in STAGES:
            rs = runs_for(stage, "render", sc)
            if not rs:
                continue
            lo, hi = spread(rs, lambda r: r["fps_avg"])
            lines.append("| %s | %d | %s | %d | %.2f (%.2f–%.2f) | %.2f | %.1f | %.1f | %.1f | %.1f | %.2f | %.1f | %.0f | %.0f | %.0f |" % (
                sc, g, label, len(rs), avg(rs, lambda r: r["fps_avg"]), lo, hi, avg(rs, lambda r: r["fps_1pct_low"]),
                avg(rs, lambda r: m(r, "frame_ms")), avg(rs, lambda r: m(r, "frame_ms", "p95")),
                avg(rs, lambda r: m(r, "render_cpu_ms")), avg(rs, lambda r: m(r, "render_gpu_ms")),
                avg(rs, lambda r: m(r, "scripts_physics_ms") + m(r, "scripts_process_ms")),
                avg(rs, lambda r: m(r, "other_ms")), avg(rs, lambda r: m(r, "draw_calls")),
                avg(rs, lambda r: m(r, "objects")), avg(rs, lambda r: m(r, "primitives"))))
    # Headless.
    lines += ["", "## Headless CPU runs (`--fixed-fps 60`: one physics tick per frame, no rendering)", "",
              "| Scenario | Guards | Stage | Runs | CPU frame ms mean | p95 | max | Scripts physics ms | Scripts process ms | Guard AI ms / tick | Guard presentation ms | Other ms (physics engine, navigation, tree) |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for sc, g in SCENARIOS:
        for stage, label in (STAGES[0], STAGES[2]):
            rs = runs_for(stage, "headless", sc)
            if not rs:
                continue
            lines.append("| %s | %d | %s | %d | %.3f | %.3f | %.2f | %.3f | %.3f | %.3f | %.3f | %.3f |" % (
                sc, g, label, len(rs), avg(rs, lambda r: m(r, "frame_ms")), avg(rs, lambda r: m(r, "frame_ms", "p95")),
                avg(rs, lambda r: m(r, "frame_ms", "max")), avg(rs, lambda r: m(r, "scripts_physics_ms")),
                avg(rs, lambda r: m(r, "scripts_process_ms")), avg(rs, lambda r: r["guard_ai_ms_per_tick"]),
                avg(rs, lambda r: m(r, "guard_presentation_ms")), avg(rs, lambda r: m(r, "other_ms"))))
    # Scaling.
    scaling = sorted(load("after_2splits_2048/cpu_scaling/npcs_*"), key=lambda r: r["guards"])
    lines += ["", "## CPU cost by guard count (headless, after)", "",
              "| Guards | CPU frame ms mean | p95 | Guard AI ms / tick | per guard | Guard presentation ms | Other ms | Static memory MB | Objects |",
              "|---|---|---|---|---|---|---|---|---|"]
    for r in scaling:
        lines.append("| %d | %.3f | %.3f | %.3f | %.4f | %.3f | %.3f | %.1f | %.0f |" % (
            r["guards"], m(r, "frame_ms"), m(r, "frame_ms", "p95"), r["guard_ai_ms_per_tick"],
            r["guard_ai_ms_per_tick_per_guard"], m(r, "guard_presentation_ms"), m(r, "other_ms"),
            m(r, "static_mem_mb"), m(r, "object_count")))
    # Diagnostics.
    diag = load("diag/*")
    lines += ["", "## What each part costs (rendering, normal scenario, 20 s, before the optimisation)", "",
              "| Run | Switched off | Avg FPS | Frame ms | Render CPU ms | Draw calls | Objects |", "|---|---|---|---|---|---|---|"]
    for r in sorted(diag, key=lambda r: -m(r, "frame_ms")):
        name = os.path.basename(r["_dir"])
        lines.append("| %s | %s | %.2f | %.1f | %.1f | %.0f | %.0f |" % (name, r.get("disabled") or ("— (640×360)" if "res_" in name else "—"),
                     r["fps_avg"], m(r, "frame_ms"), m(r, "render_cpu_ms"), m(r, "draw_calls"), m(r, "objects")))
    # Memory.
    long = load("after_2splits_2048/headless/long_normal_300s")
    if long:
        rows = list(csv.DictReader(open(os.path.join(long[0]["_dir"], "frames.csv"))))
        n = len(rows)
        lines += ["", "## Memory over 300 s (headless, normal scenario)", "", "| Time | Static memory MB | Objects | Nodes |", "|---|---|---|---|"]
        for i in range(0, 11, 2):
            row = rows[min(int(i * (n - 1) / 10), n - 1)]
            lines.append("| %d s | %.2f | %.0f | %.0f |" % (i * 30, float(row["static_mem_mb"]), float(row["object_count"]), float(row["node_count"])))
    open(os.path.join(HERE, "results.md"), "w").write("\n".join(lines) + "\n")


def charts():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 10, "figure.facecolor": SURFACE})

    # 1. Frame-time breakdown, before vs after, per scenario.
    fig, ax = plt.subplots(figsize=(9, 4.6))
    parts = [("Rendering", lambda r: m(r, "render_cpu_ms")),
             ("Scripts (physics ticks)", lambda r: m(r, "scripts_physics_ms")),
             ("Scripts (process)", lambda r: m(r, "scripts_process_ms")),
             ("Other (physics engine, navigation, tree)", lambda r: m(r, "other_ms"))]
    labels, x = [], 0
    for sc, g in SCENARIOS:
        for stage, short in (("baseline", "before"), ("after_2splits_2048", "after")):
            rs = runs_for(stage, "render", sc)
            bottom = 0.0
            for i, (name, fn) in enumerate(parts):
                v = avg(rs, fn)
                ax.bar(x, v, 0.7, bottom=bottom, color=SERIES[i], edgecolor=SURFACE, linewidth=2,
                       label=name if x == 0 else None)
                bottom += v
            ax.text(x, bottom + 2, "%.0f ms" % avg(rs, lambda r: m(r, "frame_ms")), ha="center", color=INK, fontsize=9)
            labels.append("%s\n%s (%d)" % (short, sc, g))
            x += 1
        x += 0.5
    ticks = [0, 1, 2.5, 3.5, 5, 6]
    ax.set_xticks(ticks, labels)
    style(ax, "Mean frame time by part, before and after (llvmpipe, 1280×720)", "milliseconds per frame")
    ax.legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.18), ncol=2, labelcolor=INK2)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "chart_frame_breakdown.png"), dpi=130)
    plt.close(fig)

    # 2. FPS before / after.
    fig, ax = plt.subplots(figsize=(8, 4))
    for i, (sc, g) in enumerate(SCENARIOS):
        for j, (stage, col, name) in enumerate((("baseline", BEFORE, "Before"), ("after_2splits_2048", AFTER, "After"))):
            rs = runs_for(stage, "render", sc)
            v = avg(rs, lambda r: r["fps_avg"])
            low = avg(rs, lambda r: r["fps_1pct_low"])
            xpos = i * 2.6 + j
            ax.bar(xpos, v, 0.9, color=col, edgecolor=SURFACE, linewidth=2, label=name if i == 0 else None)
            ax.text(xpos, v + 0.2, "%.1f" % v, ha="center", color=INK, fontsize=9)
            ax.plot([xpos - 0.35, xpos + 0.35], [low, low], color=INK, linewidth=2,
                    label="1% low" if i == 0 and j == 0 else None)
    ax.set_xticks([0.5, 3.1, 5.7], ["normal (3 guards)", "several (8)", "stress (24)"])
    style(ax, "Average FPS (bar) and 1% low FPS (line), llvmpipe 1280×720", "frames per second")
    ax.legend(frameon=False, labelcolor=INK2)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "chart_fps.png"), dpi=130)
    plt.close(fig)

    # 3. Diagnostics.
    diag = sorted(load("diag/*"), key=lambda r: m(r, "render_cpu_ms"))
    fig, ax = plt.subplots(figsize=(8, 5))
    nice = {"base1": "baseline (run 1)", "base2": "baseline (run 2)", "no_shadows": "sun shadows off",
            "no_omni": "omni lights off", "no_books": "books hidden", "no_dressing": "all decoration hidden",
            "no_book_shadows": "books cast no shadow (already so)", "no_shadow_splits": "sun shadow 2 cascades",
            "no_shadow_size": "shadow atlas 2048", "no_shadow_size+splits": "2 cascades + atlas 2048",
            "no_shadow_distance": "shadow distance 40 m", "no_hud": "all UI layers hidden",
            "res_640x360": "resolution 640×360"}
    diag = sorted(diag, key=lambda r: m(r, "frame_ms"))
    names = [nice.get(os.path.basename(r["_dir"]), os.path.basename(r["_dir"])) for r in diag]
    vals = [m(r, "frame_ms") for r in diag]
    cols = [BEFORE if n.startswith("baseline") else SERIES[0] for n in names]
    ax.barh(range(len(diag)), vals, color=cols, edgecolor=SURFACE, linewidth=2)
    for i, v in enumerate(vals):
        ax.text(v + 1, i, "%.0f" % v, va="center", color=INK, fontsize=9)
    ax.set_yticks(range(len(diag)), names)
    style(ax, "Frame time with one change (normal scenario, before)", "")
    ax.xaxis.grid(True, color=GRID)
    ax.yaxis.grid(False)
    ax.set_xlabel("mean frame time, ms (llvmpipe, 1280×720, 20 s each)", color=INK2)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "chart_diagnostics.png"), dpi=130)
    plt.close(fig)

    # 4. CPU scaling.
    scaling = sorted(load("after_2splits_2048/cpu_scaling/npcs_*"), key=lambda r: r["guards"])
    fig, ax = plt.subplots(figsize=(8, 4.2))
    gs = [r["guards"] for r in scaling]
    series = [("Total CPU frame", lambda r: m(r, "frame_ms")),
              ("Other (physics engine, navigation, tree)", lambda r: m(r, "other_ms")),
              ("Guard AI + vision + hearing", lambda r: r["guard_ai_ms_per_tick"]),
              ("Guard animation / presentation", lambda r: m(r, "guard_presentation_ms"))]
    for i, (name, fn) in enumerate(series):
        ys = [fn(r) for r in scaling]
        ax.plot(gs, ys, color=SERIES[i], linewidth=2, marker="o", markersize=5, label=name)
        ax.text(gs[-1] + 0.8, ys[-1], "%.2f" % ys[-1], va="center", color=INK, fontsize=9)
    ax.set_xticks(gs)
    style(ax, "CPU cost per frame by guard count (headless, one physics tick per frame)", "milliseconds")
    ax.set_xlabel("guards", color=INK2)
    ax.legend(frameon=False, labelcolor=INK2)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "chart_cpu_scaling.png"), dpi=130)
    plt.close(fig)

    # 5. Frame-time series, normal scenario run 1.
    fig, ax = plt.subplots(figsize=(9, 3.8))
    for stage, col, name in (("baseline", BEFORE, "Before"), ("after_2splits_2048", AFTER, "After")):
        path = os.path.join(HERE, stage, "render", "normal_r1", "frames.csv")
        rows = list(csv.DictReader(open(path)))
        t, acc = [], 0.0
        for r in rows:
            acc += float(r["frame_ms"]) / 1000.0
            t.append(acc)
        ax.plot(t, [float(r["frame_ms"]) for r in rows], color=col, linewidth=1.5, label=name)
    style(ax, "Frame time over the run (normal scenario, run 1)", "ms per frame")
    ax.set_xlabel("wall-clock seconds into the measured part", color=INK2)
    ax.legend(frameon=False, labelcolor=INK2)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "chart_frametime_series.png"), dpi=130)
    plt.close(fig)


if __name__ == "__main__":
    tables()
    charts()
    print("wrote results.md and charts in", HERE)
