extends SceneTree

## Compares two level reports (metrics.json from tools/level_report.gd) and
## writes a before/after markdown table:
##
##   godot --headless --path . --script res://tools/level_compare.gd -- --before=docs/level/v0 --after=docs/level/v1
##
## Writes <after>/compare.md.


func _init() -> void:
	var args := {}
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--") and a.contains("="):
			args[a.substr(2, a.find("=") - 2)] = a.substr(a.find("=") + 1)
	var before := _load("res://" + args.get("before", ""))
	var after := _load("res://" + args.get("after", ""))
	if before.is_empty() or after.is_empty():
		push_error("Usage: -- --before=docs/level/vA --after=docs/level/vB")
		quit(1)
		return
	var lines: Array[String] = []
	lines.append("# %s → %s" % [before.version, after.version])
	lines.append("")
	lines.append("Generated by `tools/level_compare.gd` from the two versions' `metrics.json`.")
	lines.append("")
	lines.append("## Totals")
	lines.append("")
	lines.append("| Metric | %s | %s | Change |" % [before.version, after.version])
	lines.append("|---|---|---|---|")
	for key in ["exposure_pct", "exposure_crouched_pct", "safe_pct", "seen_pct", "near_cover_pct", "cover_props", "low_cover_props", "walkable", "navmesh_polygons"]:
		lines.append(_row(key, before.totals.get(key, 0), after.totals.get(key, 0)))
	lines.append("")
	lines.append("## Rooms: mean exposure standing / crouched, safe floor")
	lines.append("")
	lines.append("| Room | %s | %s |" % [before.version, after.version])
	lines.append("|---|---|---|")
	var rooms: Array = after.rooms.keys()
	for r in before.rooms:
		if not r in rooms:
			rooms.append(r)
	rooms.sort()
	for r in rooms:
		lines.append("| %s | %s | %s |" % [r, _room(before.rooms.get(r, {})), _room(after.rooms.get(r, {}))])
	lines.append("")
	lines.append("## Routes: length, mean exposure, peak exposure")
	lines.append("")
	lines.append("| Route | %s | %s |" % [before.version, after.version])
	lines.append("|---|---|---|")
	for name in after.routes:
		lines.append("| %s | %s | %s |" % [name, _route(before.routes.get(name, {})), _route(after.routes[name])])
	lines.append("")
	lines.append("## Hiding spots: exposure crouched inside")
	lines.append("")
	lines.append("| Carrel | %s | %s |" % [before.version, after.version])
	lines.append("|---|---|---|")
	var spots := {}
	for h in before.get("hiding_spots", []):
		spots[h.name] = ["%.1f%%" % h.exposure_crouched_pct, "—"]
	for h in after.get("hiding_spots", []):
		spots[h.name] = [spots.get(h.name, ["—"])[0], "%.1f%%" % h.exposure_crouched_pct]
	for name in spots:
		lines.append("| %s | %s | %s |" % [name, spots[name][0], spots[name][1]])
	lines.append("")
	lines.append("## Patrols: points, waits, loop")
	lines.append("")
	lines.append("| Guard | %s | %s |" % [before.version, after.version])
	lines.append("|---|---|---|")
	var guards := {}
	for p in before.patrols:
		guards[p.name] = [p, {}]
	for p in after.patrols:
		guards[p.name] = [guards.get(p.name, [{}])[0], p]
	for g in guards:
		lines.append("| %s | %s | %s |" % [g, _patrol(guards[g][0]), _patrol(guards[g][1])])
	var out: String = "res://" + args.after + "/compare.md"
	var file := FileAccess.open(out, FileAccess.WRITE)
	file.store_string("\n".join(lines) + "\n")
	print("Compare → %s" % out)
	quit(0)


func _load(dir: String) -> Dictionary:
	var file := FileAccess.open(dir.path_join("metrics.json"), FileAccess.READ)
	if file == null:
		return {}
	var parsed = JSON.parse_string(file.get_as_text())
	return parsed if parsed is Dictionary else {}


func _row(key: String, a, b) -> String:
	var unit := "%" if key.ends_with("_pct") else ""
	var delta: float = float(b) - float(a)
	return "| %s | %s%s | %s%s | %s%s%s |" % [key, _num(a), unit, _num(b), unit, "+" if delta > 0 else "", _num(delta), unit]


func _num(v) -> String:
	var f := float(v)
	return str(int(f)) if is_equal_approx(f, roundf(f)) else "%.1f" % f


func _room(r: Dictionary) -> String:
	if r.is_empty():
		return "—"
	return "%.1f%% / %.1f%%, safe %.0f%%" % [r.exposure_pct, r.exposure_crouched_pct, r.safe_pct]


func _route(r: Dictionary) -> String:
	if r.is_empty():
		return "—"
	return "%.1f m, %.1f%%, peak %.0f%% at (%.1f, %.1f)" % [r.length_m, r.mean_exposure_pct, r.peak_exposure_pct, r.peak_at[0], r.peak_at[1]]


func _patrol(p: Dictionary) -> String:
	if p.is_empty():
		return "—"
	var pts := ", ".join(p.points.map(func(v): return "(%.1f, %.1f)" % [v[0], v[1]]))
	var waits := "/".join(p.waits.map(func(w): return "%.0f" % w))
	return "%s; waits %s s; %.0f m, %.0f s" % [pts, waits, p.length_m, p.loop_seconds]
